# Generated by Django 5.2.6 on 2025-10-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='media/room_images'),
        ),
        migrations.AddField(
            model_name='room',
            name='second_image',
            field=models.FileField(blank=True, null=True, upload_to='media/room_images'),
        ),
    ]
