# Generated by Django 5.2.7 on 2025-10-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_bedtype_room_number_of_beds_room_services_room_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedtype',
            name='occupancy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='occupancy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
