# Generated by Django 5.2.7 on 2025-11-01 16:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_comment'),
        ('rooms', '0004_alter_bedtype_occupancy_alter_roomtype_occupancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['serial']},
        ),
        migrations.AddField(
            model_name='room',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.comment'),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
