# Generated by Django 5.2.7 on 2026-01-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_comment'),
        ('rooms', '0005_alter_room_options_room_comment_room_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.comment'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='media/room_images'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='person_occupancy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='second_image',
            field=models.FileField(blank=True, null=True, upload_to='media/room_images'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='services',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
