# Generated by Django 5.2.7 on 2026-01-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_roomtype_comment_roomtype_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='person_occupancy',
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='media/room_type_images'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='second_image',
            field=models.FileField(blank=True, null=True, upload_to='media/room_type_images'),
        ),
    ]
