# Generated by Django 5.2.7 on 2026-01-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_remove_roomtype_person_occupancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='bed_type',
            field=models.ManyToManyField(blank=True, null=True, to='rooms.bedtype'),
        ),
    ]
