# Generated by Django 5.2.10 on 2026-02-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_roomreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreview',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
