# Generated by Django 5.2.7 on 2025-10-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('rooms', '0004_alter_bedtype_occupancy_alter_roomtype_occupancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='room',
        ),
        migrations.AddField(
            model_name='transaction',
            name='room',
            field=models.ManyToManyField(blank=True, null=True, to='rooms.room'),
        ),
    ]
