# Generated by Django 5.2.4 on 2026-02-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_transaction_room_transaction_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='booking_check_in',
            field=models.DateField(blank=True, help_text='Check-in date for booking', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='booking_check_out',
            field=models.DateField(blank=True, help_text='Check-out date for booking', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='booking_guests_count',
            field=models.IntegerField(default=1, help_text='Number of guests'),
        ),
    ]
