# Generated by Django 5.2.10 on 2026-02-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_transaction_booking_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='booking_dates_json',
            field=models.JSONField(blank=True, help_text='Per-room booking dates as JSON', null=True),
        ),
    ]
