# Generated by Django 5.2.4 on 2026-02-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_transaction_booking_dates_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'verbose_name': 'Payment Gateway', 'verbose_name_plural': 'Payment Gateways'},
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='api_url',
            field=models.URLField(blank=True, help_text='API base URL for payment gateway', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='gateway_type',
            field=models.CharField(choices=[('sslcommerz', 'SSL-Commerz'), ('bkash', 'bKash')], default='sslcommerz', help_text='Payment gateway type', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant_invoice_number',
            field=models.CharField(blank=True, help_text='Merchant invoice number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_gateway',
            field=models.CharField(choices=[('sslcommerz', 'SSL-Commerz'), ('bkash', 'bKash')], default='sslcommerz', help_text='Payment method used', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(blank=True, help_text='bKash payment ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trx_id',
            field=models.CharField(blank=True, help_text='bKash transaction ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='store_id',
            field=models.CharField(blank=True, help_text='Store ID or App Key', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='store_pass',
            field=models.CharField(blank=True, help_text='Store Password or App Secret', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_tran_id',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_brand',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_issuer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_issuer_country',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_issuer_country_code',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_no',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='risk_level',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='risk_title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='store_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='val_id',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='verify_sign',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='verify_sign_sha2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
