# Generated by Django 5.2.4 on 2026-02-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_paymentgateway_options_paymentgateway_api_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'verbose_name': 'Payment Gateway', 'verbose_name_plural': 'Payment Gateway'},
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='api_url',
            field=models.TextField(blank=True, help_text='For bKash: username:password format', null=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_type',
            field=models.CharField(choices=[('SSL-Commerz', 'SSL-Commerz'), ('bKash', 'bKash')], default='SSL-Commerz', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='store_id',
            field=models.CharField(blank=True, help_text='SSL Store ID or bKash App Key', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='store_pass',
            field=models.CharField(blank=True, help_text='SSL Store Password or bKash App Secret', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_gateway',
            field=models.CharField(default='SSL-Commerz', help_text='Payment gateway used (SSL-Commerz, bKash, COD)', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(blank=True, help_text='bKash Payment ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trx_id',
            field=models.CharField(blank=True, help_text='bKash Transaction ID', max_length=100, null=True),
        ),
    ]
