# Generated by Django 5.2.10 on 2026-02-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_paymentgateway_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgateway',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='gateway_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='merchant_invoice_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_gateway',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='trx_id',
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='store_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='store_pass',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='store_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tran_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
