# Generated by Django 5.2.7 on 2025-10-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Guest/%Y/%M', verbose_name='Guest Image'),
        ),
        migrations.AddField(
            model_name='guest',
            name='nid_file',
            field=models.FileField(blank=True, null=True, upload_to='media/nid_file/%Y/%M', verbose_name='NID file upload'),
        ),
        migrations.AddField(
            model_name='guest',
            name='nid_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
