"""
Django settings for rhms project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATE_DIR =os.path.join(BASE_DIR,'templates')
STATIC_DIR =os.path.join(BASE_DIR,'static')

MEDIA_ROOT =  os.path.join(BASE_DIR , 'media') 
MEDIA_URL = '/media/'
STATICFILES_DIRS= [STATIC_DIR, ]
STATIC_URL = 'static/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mjfqn-@3@9p-m*(n_v24zht!-5ts12*7jkk#6-8u94-v*u205z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CART_SESSION_ID = 'cart'
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'rangefilter',
    'ckeditor',
    'sslcommerz_lib',
    'accounts',
    'region',
    'rhms',
    'cart',
    'rooms',
    'payment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rhms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'rhms.context_processors.site_info'

            ],
        },
    },
]

WSGI_APPLICATION = 'rhms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': [
            [ 'Format','Font', 'FontSize','Table','Undo', 'Redo',
             '-', 'Bold', 'Italic', 'Underline',
             '-', 'RemoveFormat','Cut', 'Copy', 'Paste', '-', 'SelectAll',
             
             '-', 'Maximize',
             
            ],
        ],
        
        'height':'100%',
        'width': 'full',
        'toolbarCanCollapse': True,

    },
    
    'awesome_ckeditor': {
        'toolbar': [
            [ 'Format','Undo', 'Redo',
             
             '-', 'Maximize',
             
            ],
        ],  
        'width': 'auto',
        'toolbarCanCollapse': True,
    },
     'body_ckeditor': {
        'toolbar': [
            ['Undo', 'Redo',
             '-', 'Bold', 'Italic', 'Underline',
             '-', 'Link', 'Unlink', 'Anchor',
             '-', 'Format',
             
             '-', 'Maximize',
             
            ],
        ],  
        'width': '95%',
        'toolbarCanCollapse': True,
        'height': '50%',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Messages framework
MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'
MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.ERROR: 'danger',
}

# reCAPTCHA (v2 Checkbox)
RECAPTCHA_SITE_KEY = os.environ.get('RECAPTCHA_SITE_KEY', '6LfKnGMsAAAAADMTciEbrIVNlVAB3fa2LpDoPfEa')
RECAPTCHA_SECRET_KEY = os.environ.get('RECAPTCHA_SECRET_KEY', '6LfKnGMsAAAAAEy1rYVHlPqqTBntxp18gAhPaGr1')
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')
