# Generated by Django 5.2.6 on 2025-10-01 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(max_length=100, unique=True)),
                ('slogan', models.CharField(max_length=100, unique=True)),
                ('slogan_en', models.CharField(max_length=100, unique=True)),
                ('license_no', models.CharField(max_length=25, unique=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='media/logo')),
                ('logo_en', models.FileField(blank=True, null=True, upload_to='media/logo')),
                ('logo_opacity', models.FileField(blank=True, null=True, upload_to='media/logo')),
                ('logo_opacity_en', models.FileField(blank=True, null=True, upload_to='media/logo')),
                ('monogram', models.FileField(blank=True, null=True, upload_to='media/logo')),
                ('monogram_en', models.FileField(blank=True, null=True, upload_to='media/logo')),
                ('link', models.URLField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.district')),
                ('upazilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.upazilla')),
            ],
            options={
                'verbose_name': 'প্রতিষ্ঠানের বিবরণ',
                'verbose_name_plural': 'প্রতিষ্ঠানের বিবরণ',
                'ordering': ['title_en'],
            },
        ),
    ]
