# Generated by Django 5.2.7 on 2025-10-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('title_en', models.CharField(max_length=250, unique=True)),
                ('sub_title', models.CharField(blank=True, max_length=250, null=True)),
                ('sub_title_en', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/carousel')),
            ],
        ),
    ]
