# Generated by Django 5.2.7 on 2025-10-23 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_guest_image_guest_nid_file_guest_nid_number'),
        ('payment', '0001_initial'),
        ('rhms', '0002_carousel'),
        ('rooms', '0004_alter_bedtype_occupancy_alter_roomtype_occupancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(blank=True, max_length=150, null=True)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('booked_on', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.guest')),
                ('room', models.ManyToManyField(blank=True, null=True, to='rooms.room')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.transaction')),
            ],
        ),
    ]
