# Generated by Django 5.2.7 on 2025-10-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhms', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_person',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
