# Generated by Django 5.2.7 on 2025-11-28 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhms', '0004_booking_number_of_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'লিংকসমূহ',
                'verbose_name_plural': 'লিংকসমূহ',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='ColorRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.CharField(blank=True, max_length=250, null=True)),
                ('weather', models.CharField(blank=True, max_length=250, null=True)),
                ('service', models.CharField(blank=True, max_length=250, null=True)),
                ('card', models.CharField(blank=True, max_length=250, null=True)),
                ('heading', models.CharField(blank=True, max_length=250, null=True)),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True)),
                ('navitem', models.CharField(blank=True, max_length=250, null=True)),
                ('navbar_collaps', models.CharField(blank=True, max_length=250, null=True)),
                ('member_registration', models.CharField(blank=True, max_length=250, null=True)),
                ('internal', models.CharField(blank=True, max_length=250, null=True)),
                ('other_text', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('hotel_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rhms.hoteldetails')),
            ],
            options={
                'verbose_name': 'কালারসমূহ',
                'verbose_name_plural': 'কালারসমূহ',
                'ordering': ['serial'],
            },
        ),
    ]
