# Generated by Django 5.2.7 on 2025-11-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhms', '0005_importantlinks_colorroot'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetails',
            name='title_short',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hoteldetails',
            name='title_short_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetails',
            name='license_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetails',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetails',
            name='slogan_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
