# Generated by Django 5.2.4 on 2026-02-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhms', '0006_hoteldetails_title_short_hoteldetails_title_short_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
