# Generated by Django 5.2.6 on 2025-10-01 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='post_office',
        ),
        migrations.RemoveField(
            model_name='village',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='union',
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('ward', models.CharField(blank=True, max_length=50, null=True, verbose_name='ওয়ার্ড নং ')),
                ('village_or_street', models.CharField(blank=True, max_length=50, null=True, verbose_name=' গ্রাম/মহল্লা')),
                ('post_office', models.CharField(blank=True, max_length=50, null=True, verbose_name='ডাকঘর ')),
                ('Others', models.CharField(blank=True, max_length=500, null=True, verbose_name='অন্য ঠিকানা ')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.district', verbose_name=' জেলা ')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.division', verbose_name=' বিভাগ ')),
                ('upazilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.upazilla', verbose_name='উপজেলা ')),
            ],
            options={
                'verbose_name': 'ঠিকানা',
                'verbose_name_plural': 'ঠিকানা',
                'ordering': ['serial'],
            },
        ),
        migrations.DeleteModel(
            name='PostOffice',
        ),
        migrations.DeleteModel(
            name='Village',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
