# Generated by Django 5.2.6 on 2025-10-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_remove_village_post_office_remove_village_ward_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
    ]
