# Generated by Django 5.2.7 on 2026-01-09 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_rename_adress_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Others',
            new_name='others',
        ),
    ]
